version: 2
updates:
  # Configuration for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions in a daily basis
      interval: "daily"
    labels:
      - 'github actions'
    assignees:
      - "mariano-aguero"
    reviewers:
      - "mariano-aguero"
  # Configuration for npm, reports
  - package-ecosystem: "npm"
    directory: '/dapps/reports'
    schedule:
      interval: 'daily'
    assignees:
        - "mariano-aguero"
    reviewers:
      - "mariano-aguero"
    versioning-strategy: 'increase'
    labels:
      - 'dependencies'
    pull-request-branch-name:
      separator: '-'
    commit-message:
      # cause a release for non-dev-deps
      prefix: fix(deps)
      # no release for dev-deps
      prefix-development: chore(dev-deps)
  # Configuration for npm, panic-button
  - package-ecosystem: "npm"
    directory: '/dapps/panic-button'
    schedule:
      interval: 'daily'
    assignees:
      - "mariano-aguero"
    reviewers:
      - "mariano-aguero"
    versioning-strategy: 'increase'
    labels:
      - 'dependencies'
    pull-request-branch-name:
      separator: '-'
    commit-message:
      # cause a release for non-dev-deps
      prefix: fix(deps)
      # no release for dev-deps
      prefix-development: chore(dev-deps)
  # Configuration for npm, shared
  - package-ecosystem: "npm"
    directory: '/shared'
    schedule:
      interval: 'daily'
    assignees:
      - "mariano-aguero"
    reviewers:
      - "mariano-aguero"
    versioning-strategy: 'increase'
    labels:
      - 'dependencies'
    pull-request-branch-name:
      separator: '-'
    commit-message:
      # cause a release for non-dev-deps
      prefix: fix(deps)
      # no release for dev-deps
      prefix-development: chore(dev-deps)
