version: 2
updates:
  # Configuration for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions in a daily basis
      interval: "daily"
    reviewers:
      - "mariano-aguero"
  # Configuration for npm
  - package-ecosystem: "npm"
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - "mariano-aguero"
    versioning-strategy: 'increase'
    labels:
      - 'dependencies'
    pull-request-branch-name:
      separator: '-'
    commit-message:
      # cause a release for non-dev-deps
      prefix: fix(deps)
      # no release for dev-deps
      prefix-development: chore(dev-deps)
