# Args
ARG PORT=3000
ARG NODE_ENV=development

ARG VERSION=lts-alpine
FROM node:${VERSION} AS builder

# Set env vars
ENV NODE_ENV=${NODE_ENV}
ENV NEXT_TELEMETRY_DISABLED 1
ENV NEXTJS_IGNORE_ESLINT=1
ENV NEXTJS_IGNORE_TYPECHECK=0
ENV PORT=${PORT}

# Set working directory
WORKDIR /app

# Install wget
RUN apk --no-cache add openssl wget

# Copy all files
COPY . .

# Install dependencies
RUN yarn install --frozen-lockfile

WORKDIR /app

# Build app
RUN --mount=type=secret,id=env,dst=/.env yarn run build

# Expose the listening port
EXPOSE ${PORT}

# Run yarn start script when container starts
CMD crond && yarn start
