name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-20.04
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thanks for creating an issue. We will try to fix it and close it ASAP'
          pr-message: "Thanks for contributing on this repo and giving it your time. We'll check it and merge, if no issue found"
