name: PR Deployment CI/CD

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened

jobs:

  docker_build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set PR_SHA as Environment Variable
        run: |
          PR_SHA=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)
          echo "PR_SHA=${PR_SHA}" >> $GITHUB_ENV

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: registry.digitalocean.com/karpatkey/karpatkey-dapps-monorepo
          tags: |
            type=raw,value=pr${{ env.PR_SHA }}
            
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=true

  deploy:
    runs-on: self-hosted
    needs: docker_build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Kubernetes
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}

    - name: Build and Deploy
      run: |
        PR_SHA=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)

        # Use PR_SHA in your deploy script
        ./deploy-script.sh $PR_SHA

    - name: Clean up
      run: |
        rm deployment-temp.yaml
        rm ingress-temp.yaml
