name: Build and Push to Docker Registry

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - develop
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a three jobs called "test_app", "build", "push_on_docker"
  
  docker:
    
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: registry.digitalocean.com/karpatkey/karpatkey-dapps-monorepo
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}
            type=raw,value={{branch}}
            type=semver,pattern={{version}},value=v1.0.0
            develop


      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: build and Push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile
          build-args: |
            "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}"

  update-deployment:
    needs: docker
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
    - uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}
    - run: kubectl delete pod -n karpatkey-dapps-monorepo -l app=karpatkey-dapps-monorepo --force