name: Build and Push to Docker Registry

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events for the main branch
  push:
    branches:
      - main
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker_main:
    if: github.ref == 'refs/heads/main' # Run only for the main branch
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: registry.digitalocean.com/karpatkey/karpatkey-dapps-monorepo
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}
            type=raw,value={{branch}}
            
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile*') }}

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile
          

  docker_develop:
    if: github.ref == 'refs/heads/develop' # Run only for the develop branch
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: registry.digitalocean.com/karpatkey/karpatkey-dapps-monorepo
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}
            type=raw,value={{branch}}

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile*') }}
        
      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile
          

  update_main_deployment:
    if: github.ref == 'refs/heads/main' # Run only for the main branch
    needs: docker_main
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - run: kubectl delete pod -n karpatkey-dapps-monorepo -l app=karpatkey-dapps-monorepo --force

  update_develop_deployment:
    if: github.ref == 'refs/heads/develop' # Run only for the develop branch
    needs: docker_develop
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - run: kubectl delete pod -n develop-karpatkey-dapps-monorepo -l app=develop-karpatkey-dapps-monorepo --force
